remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Juan Camilo Ossa Quintero
submodulo: Programación de Aplicaciones Móviles I
periodo: 2023-4
url_foto: https://firebasestorage.googleapis.com/v0/b/fotos-446a5.appspot.com/o/Captura%20de%20pantalla%202023-09-27%20192423.png?alt=media&token=1a7a86d4-a934-4fb1-8a2a-4fc95168ec0f&_gl=1*d5fb5b*_ga*MTk3NjYwNjA3NC4xNjk1ODYwMjYz*_ga_CW55HF8NVT*MTY5NTg2MDI2Mi4xLjEuMTY5NTg2MTI4Mi45LjAuMA..